### ISSUE TITLE
Jest failure

### ISSUE THREAD

**Issue by tharper1977** [wnabil/ngx-notification-bar#6]
I am unable to run tests using jest.   I am getting the following error:
<root-dir>\>ng test
 FAIL  src/app/loadFile/file-upload.component.spec.ts
  ? Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    <root-dir>\node_modules\ngx-notification-bar\release\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './src/notification-bar.module';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      2 | import { FileUploader, FileDropDirective } from 'ng2-file-upload/ng2-file-upload';
      3 | import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
    > 4 | import { NotificationBarService, NotificationType } from 'ngx-notification-bar/release';
        | ^
      5 |
      6 | @Component({
      7 |   selector: './app-file-upload',

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/app/loadFile/file-upload.component.ts:4:1)
      at Object.<anonymous> (src/app/loadFile/file-upload.component.spec.ts:5:1)

 FAIL  src/app/app.component.spec.ts (14.903s)
  AppComponent
    × should create the app (866ms)
    × should have as title 'FlowPlan' (258ms)
    × should render a drag and drop area (239ms)
    × should render a file selector (205ms)

  ? AppComponent should create the app

    Error

      Error: Template parse errors:
      'notification-bar' is not a known element:
      1. If 'notification-bar' is an Angular component, then verify that it is part of this module.
      2. If 'notification-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<notification-bar></notification-bar>
      <div style="text-align:center">
        <h1>Welcome to {{ title }}!"): ng:///DynamicTestModule/AppComponent.html@0:0
      'app-file-upload' is not a known element:
      1. If 'app-file-upload' is an Angular component, then verify that it is part of this module.
      2. If 'app-file-upload' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      </div>

      [ERROR ->]<app-file-upload></app-file-upload>
      "): ng:///DynamicTestModule/AppComponent.html@5:0
      at syntaxError (../packages/compiler/src/util.ts:100:17)
      at TemplateParser.Object.<anonymous>.TemplateParser.parse (../packages/compiler/src/template_parser/template_parser.ts:106:13)
      at JitCompiler.Object.<anonymous>.JitCompiler._parseTemplate (../packages/compiler/src/jit/compiler.ts:297:33)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileTemplate (../packages/compiler/src/jit/compiler.ts:275:11)
      at ../packages/compiler/src/jit/compiler.ts:206:42
          at Set.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileComponents (../packages/compiler/src/jit/compiler.ts:206:15)
      at ../packages/compiler/src/jit/compiler.ts:117:12
      at Object.then (../packages/compiler/src/util.ts:89:74)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileModuleAndAllComponents (../packages/compiler/src/jit/compiler.ts:115:22)
      at JitCompiler.Object.<anonymous>.JitCompiler.compileModuleAndAllComponentsAsync (../packages/compiler/src/jit/compiler.ts:69:33)
      at CompilerImpl.Object.<anonymous>.CompilerImpl.compileModuleAndAllComponentsAsync (../packages/platform-browser-dynamic/src/compiler_factory.ts:68:27)
      at TestingCompilerImpl.Object.<anonymous>.TestingCompilerImpl.compileModuleAndAllComponentsAsync (../../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:57:27)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.compileComponents (../../packages/core/testing/src/test_bed.ts:385:27)
      at Function.Object.<anonymous>.TestBedViewEngine.compileComponents (../../packages/core/testing/src/test_bed.ts:168:66)
      at src/app/app.component.spec.ts:29:8
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:106:39)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:125:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.runGuarded (node_modules/zone.js/dist/zone.js:151:47)
      at runInTestZone (node_modules/zone.js/dist/async-test.js:234:29)
      at node_modules/zone.js/dist/async-test.js:168:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length.done (node_modules/jest-zone-patch/index.js:51:29)

  ? AppComponent should create the app

    Error

      Error: Template parse errors:
      'notification-bar' is not a known element:
      1. If 'notification-bar' is an Angular component, then verify that it is part of this module.
      2. If 'notification-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<notification-bar></notification-bar>
      <div style="text-align:center">
        <h1>Welcome to {{ title }}!"): ng:///DynamicTestModule/AppComponent.html@0:0
      'app-file-upload' is not a known element:
      1. If 'app-file-upload' is an Angular component, then verify that it is part of this module.
      2. If 'app-file-upload' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      </div>

      [ERROR ->]<app-file-upload></app-file-upload>
      "): ng:///DynamicTestModule/AppComponent.html@5:0
      at syntaxError (../packages/compiler/src/util.ts:100:17)
      at TemplateParser.Object.<anonymous>.TemplateParser.parse (../packages/compiler/src/template_parser/template_parser.ts:106:13)
      at JitCompiler.Object.<anonymous>.JitCompiler._parseTemplate (../packages/compiler/src/jit/compiler.ts:297:33)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileTemplate (../packages/compiler/src/jit/compiler.ts:275:11)
      at ../packages/compiler/src/jit/compiler.ts:206:42
          at Set.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileComponents (../packages/compiler/src/jit/compiler.ts:206:15)
      at ../packages/compiler/src/jit/compiler.ts:117:12
      at Object.then (../packages/compiler/src/util.ts:89:74)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileModuleAndAllComponents (../packages/compiler/src/jit/compiler.ts:115:22)
      at JitCompiler.Object.<anonymous>.JitCompiler.compileModuleAndAllComponentsSync (../packages/compiler/src/jit/compiler.ts:65:38)
      at CompilerImpl.Object.<anonymous>.CompilerImpl.compileModuleAndAllComponentsSync (../packages/platform-browser-dynamic/src/compiler_factory.ts:60:35)
      at TestingCompilerImpl.Object.<anonymous>.TestingCompilerImpl.compileModuleAndAllComponentsSync (../../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:52:27)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:399:28)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:602:10)
      at Function.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:251:36)
      at src/app/app.component.spec.ts:33:29
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (node_modules/jest-zone-patch/index.js:50:27)

 Here is my test case:
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NotificationBarService, NotificationType } from 'ngx-notification-bar/release';

import { FileUploadComponent } from './file-upload.component';

describe('FileUploadComponent', () => {
  let component: FileUploadComponent;
  let fixture: ComponentFixture<FileUploadComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ FileUploadComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(FileUploadComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

Hre is my component:
import { Component, OnInit } from '@angular/core';
import { FileUploader, FileDropDirective } from 'ng2-file-upload/ng2-file-upload';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NotificationBarService, NotificationType } from 'ngx-notification-bar/release';

@Component({
  selector: './app-file-upload',
  templateUrl: './file-upload.component.html',
  styleUrls: ['./file-upload.component.css']
})

export class FileUploadComponent implements OnInit {
  public uploader: FileUploader = new FileUploader({
    allowedFileType: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
  });

  public hasBaseDropZoneOver = false;

  constructor(public notificationBarService: NotificationBarService) {
  }

  ngOnInit() {
  }

  public fileOverBase(e: any): void {
    this.hasBaseDropZoneOver = e;
  }

  public dropped(event: any) {
    console.log('dropped files.');
    if (this.verifyFileCount(event)
      && this.verifyFileType(event)) {
      const file = event[0];

      try {
        this.loadFile(file);
        this.showMessage('File \'' + file.name + '\' successfully uploaded!', 5000, NotificationType.Success);
      } catch (e) {
        this.showMessage('Something went wrong while uploading file \'' + file.name + '\'!', 5000, NotificationType.Error);
      }
    }
  }

  private verifyFileCount(event: any) {
    if (event.length !== 1) {
      this.showMessage('You can only upload one file at a time!', 5000, NotificationType.Error);
      return false;
    }
    return true;
  }

  private verifyFileType(event: any) {
    if (event[0].type !== 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') {
      this.showMessage('You can only upload one excel spreadsheet!', 5000, NotificationType.Error);
      return false;
    }
    return true;
  }

  private loadFile(arg0: any): any {
    throw new Error('Method not implemented.');
  }

  private showMessage(messageToDisplay: string, delay: number, notificationType: NotificationType) {
    this.notificationBarService.create({
      message: messageToDisplay,
      hideDelay: delay,
      type: notificationType
    });
  }
}

**Comment by wnabil** [comment]
I am working currently to convert this project to use angular 7 and ng-packagr 
please wait until the next release.

**Comment by wnabil** [comment]
implemented, please check the latest version.
Thank you for your patient.
